### ISSUE TITLE
Add a changelog system

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#169]
pypa uses https://pypi.org/project/towncrier mostly, though we can also check https://github.com/nedbat/scriv as an option.

**Comment by FFY00** [comment]
My main concern is the workflow for contributors. I have never used either one of those. Could you show me a very quick/simple example of how it would look like?

**Comment by FFY00** [comment]
Nevermind, seems simple enough. Any gotchas? If not, I am happy with either one of those.

**Comment by gaborbernat** [comment]
No real gotcha other than the contributions specify fragments of the changelog, and the release needs to merge them and add them to the main chanelog.

**Comment by pganssle** [comment]
A few things to note about town crier (and changelog management in general):

1. It is designed with twisted's dev process in mind, and twisted's dev process always has a tracking issue (similar to how essentially all changes to CPython have an associated bpo issue), so it makes sense to require an issue number as part of the file name. For workflows like ours, where half the time we'll get bug reports in the form of a PR fixing the issue, it's mildly annoying that you need to make the PR, then then write the changelog after you know the PR number.
2. People are not great at picking the right category for their fragment. Best to keep the taxonomy very simple.
3. We'll need to pretty clearly signpost that we want someone to fill this out. A lot of times people just add it to a PR template checklist. `pip` and `cpython` have bots that complain if there's no news (in `pip`'s version you can add a `.trivial` stub to bypass it, with `cpython` there's a label that says to skip the news.
4.It would be a very good idea to have a style guide for these changes. Do we want present tense (Fixes...) or past tense (Fixed...). Where would we put references to the relevant issues?
5. Since we often don't do squash merges, it's probably a good idea to have a policy (even if it's a loose suggestion) about which commit the changelog goes with. Is it a free-standing commit? In the first commit of the PR? In the last commit of the PR? In the most substantive commit of the PR? The fact that we're doing rebase merges doesn't help with this (since without a merge commit we're actually throwing away the information that would give us a "PR-level" view of the git history).

**Comment by layday** [comment]
One thing to note is that scriv encodes quite a bit of information in the filename (ISO date and time, git username and branch) which pretty much ensures that contributors will have to install scriv to create changelog entries (by using the `scriv create` command).  With towncrier `echo "Fixed foo." > pr-number.bugfix` gets the job done.  Needing to know the PR number before creating a new log entry can be grating but the upside of that is that towncrier links to PRs natively - it can be used to track 'provenance'.

**Comment by gaborbernat** [comment]
Another path worth exploring is what @FFY00 suggests in #168, using commit messages as the raw source of the changelog, instead of news fragments sideloaded. There have been even tools written around this concept, see http://commitizen.github.io/cz-cli/. That being said we don't have to adopt some of these tools, but we need to have then some way to ensure those commit messages styles adhere too (some Github Action?), and we need to reformulate commit messages of contributors that don't follow the guideline (perhaps via squash the PR, and author the commit message ourselves).

**Comment by pganssle** [comment]
Commit messages serve a totally different purpose from changelogs, and they are much harder to review than files in the repository.

We should be writing these for humans to read. Grouping them conceptually (breaking changes at the top, deprecations, etc). We shouldn't be exposing random stuff like, "fix CI" or other various administrativia.

See this: https://keepachangelog.com/en/1.0.0/#bad-practices

**Comment by FFY00** [comment]
I did not propose removing the changelog entirely in favor of the git history. What I said is that I do not believe having links to endless bikeshed in PRs or issues is solving technical debt. I think that the best solution here is to document changes in the commits, creating a readable history. I still think having links to issues or PRs might be helpful, but I think I should be able to point at a commit, which would have a quick summary of the issue and the chosen solution, instead of forcing users to read dozens of messages bikesheding or debugging issues. That is my solution to the technical debt issue you brought up.

IMO we should document things properly in the commits and have a changelog file, which we can edit directly. The changelog file wouldn't have everything, just the relevant bits for end users. Being able to edit it directly allow us to order it in a nice way acording to relevancy and grouping similar changes together, better than we would be able to by using a news system with categories.

I understand this is more work, but having a proper git history is something I care about. Other projects might not feel this way, and that is completely fine. But as the person responsible for this project, I am ultimately to blame when things go wrong and/or are broken.

**Comment by layday** [comment]
Given the low volume of contributions to this repo and small number of PRs, editing the changelog directly should prove perfectly adequate.
