### ISSUE TITLE
Dynamic version from git

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#170]
What do people think to switch to https://pypi.org/project/setuptools-scm/, which generates the package version dynamically from the SCM, rather than having it hardcoded as we do today (in two places to make things worse)? virtualenv does this for example https://github.com/pypa/virtualenv/blob/main/setup.py#L7-L11

**Comment by FFY00** [comment]
This is *very* annoying when building from a tarball (not sdist). People will have to go search for the obscure `SETUPTOOLS_SCM_PRETEND_VERSION` env var to force a version -- even now I had to go look up the correct name. A release script could very easily handle this. So I am -2 on this.

**Comment by gaborbernat** [comment]
I'm +2 on this. It's very annoying to have the version be static for all commits between two releases. They're obviously not the same version all of them.

**Comment by FFY00** [comment]
Then find a solution that does not have such poor implementation for this use-case. One of the target userbase of this repo are packagers and setuptools-scm is super annoying. Just because the problem can be solved, doesn't mean we should stop caring about it. I am not +1 on the idea, -2 on setuptools-scm.

**Comment by FFY00** [comment]
Also, setuptools-scm would make the bootstraping process harder.

**Comment by layday** [comment]
hm? Why would people overwrite the version from an sdist?

**Comment by FFY00** [comment]
> tarball (not sdist)

That is not the use-case. The use-case is building from a github tarball.

**Comment by gaborbernat** [comment]
He's not talking about an sdist but rather taking a GitHub tarball...

**Comment by FFY00** [comment]
Some distros might consider that, I do not, it's usually because of security reasons. Uploading to PyPI is an extra step that could be compromised. We prefer to get the code from the source rather than a 3rd party service that authors can upload to.

**Comment by pganssle** [comment]
We should probably at least add something like `.dev0` or something close to what `setuptools_scm` would generate for non-tagged versions. That way at least the master branch won't have an identical version number to what `setuptools_scm` is doing.

Is it not possible to configure `setuptools_scm` such that we can check in the `_version,py` it generates when creating source distributions?

**Comment by gaborbernat** [comment]
> Uploading to PyPI is an extra step that could be compromised.

I consider this overzealous. Compromising a Github account (with most people not having 2FA on) is probably just as easy as compromising PyPI. But 🤷 

> Is it not possible to configure `setuptools_scm` such that we can check in the `_version,py` it generates when creating source distributions?

If you want to go on the path of a version tracked version update your best option probably is a Github Action that updates the version file upon merge to the master branch.

**Comment by pganssle** [comment]
> If you want to go on the path of a version tracked version update your best option probably is a Github Action that updates the version file upon merge to the master branch.

Well, I mean the ideal situation would be that we have a `_version.py` that works without hitting `setuptools_scm` and without building a source distribution. It doesn't need to be the version that you get when you do `pip install .` in a git checkout, which means it only needs to be updated when you want the fallback version to be updated (e.g. on release). We could make it very simple:

1. Adopt `setuptools_scm` and check in a `_version.py`
2. On every release, update the `_version.py`.
3. Add something to the release script that commits the new `_version.py` on every release.
4. Add a GHA that only runs on tags that verifies that the `_version.py` matches what you get when you do `pip install .` for the tagged version.

Assuming that `setuptools_scm` will work when a generated `_version.py` is already present in the repo, that seems like the simplest thing, because anyone using a non-standard build system should fall back to the current behavior, but anyone testing against master would still be able to do version guards against `if Version(...) > CURRENT_VERSION`.

**Comment by FFY00** [comment]
As long as it does not bring extra bootstrapping dependencies and it works on normal tarballs, I am fine.

**Comment by layday** [comment]
Well, I think the usefulness of setuptools_scm is rather diminished if we resort to creating release commits to update the 'fallback' version.  It'd also have to be pulled in as a build dependency even though it wouldn't necessarily be needed for building releases.

As for using setuptools_scm in development, I haven't found that to be very practical. The version is essentially static unless you force-reinstall the package.  If we're creating release commits, we might as well create a post-release commit and append 'dev' to it or whatever.

**Comment by webknjaz** [comment]
FWIW there's setuptools-scm-git-archive that solves the problem of installing from GitHub tags (but not arbitrary commits).

**Comment by webknjaz** [comment]
FTR here's what hypothesis does: https://hypothesis.works/articles/continuous-releases/. Maybe you'll like this workflow better.

**Comment by FFY00** [comment]
It still requires a new dependency :confused: Which is problematic when bootstraping.

If we really want to do this, I think the best solution would be to just move back to `setup.py` and generate `version` dynamically.

But I think just using a `dev` suffix after a release like @layday suggested should be good enough, even if not optimal.

**Comment by webknjaz** [comment]
@FFY00 the hypothesis way doesn't have the bootstrapping problem because it's entirely CI-based.

**Comment by pganssle** [comment]
> But I think just using a `dev` suffix after a release like @layday suggested should be good enough, even if not optimal.

I don't see why my suggestion won't work? It's simple and satisfies everyone's requirements.

@webknjaz I'd be on board with the hypothesis CD solution, but Filipe doesn't want any release automation (plus I'm not sure how happy he would be with what it does to the git history, either).

**Comment by FFY00** [comment]
> @FFY00 the hypothesis way doesn't have the bootstrapping problem because it's entirely CI-based.

I don't understand, how does this provide a version string that includes the git commit information and whatnot? Isn't that what this is about?

> I don't see why my suggestion won't work? It's simple and satisfies everyone's requirements.

It requires us to pull setuptools_scm? Or am I missing something?

> @webknjaz I'd be on board with the hypothesis CD solution, but Filipe doesn't want any release automation (plus I'm not sure how happy he would be with what it does to the git history, either).

I am *fine* with release automation, what I am not fine with is pushing release artifacts or doing any cryptographic signing via the CI.

A release script could do everything that hypothesis does, couldn't it?

**Comment by gaborbernat** [comment]
> A release script could do everything that hypothesis does, couldn't it?

Yes, with the caveat of instead of being automated you'd enforce manual only mode on the logic.

**Comment by layday** [comment]
Assuming we do adopt setuptools_scm, how would the version be updated?  I suppose we could check in the version file generated by setuptools_scm and do an editable install on release to modify it in place?  However, this does also mean that editable installs during development will dirty the tree.

**Comment by gaborbernat** [comment]
> Assuming we do adopt setuptools_scm, how would the version be updated?

In normal use, it never needs to be updated. The metadata for sdist/wheel is automatically set per the SCM (both in editable or normal install, during install/build time). In @pganssle proposal, you'd come up with some heuristic to alter this, driven by a release script that takes as its input the release tag:

- update the embedded ``_version.py`` with the release tag (the embedded ``_version.py`` is only used to get the version if there's no SCM at build time, we'd probably need to have a four-line ``setup.py`` that first tries to load and ask setuptools_scm to get the version, and if that fails to load the embedded version script),
- commit, apply the tag onto the SCM,
- build the sdist/wheel and publish to PyPI,
- push the tag above to Github (which creates the release tar bar automatically).

There's nothing implicitly bad about this workflow with the slight caveat that we need a release script.

**Comment by gaborbernat** [comment]
Here's a demo of it: https://github.com/gaborbernat/python-build/commit/15d926e87ed37df3f189793ea75ab303e0464337 👍

**Comment by ansemjo** [comment]
> He's not talking about an sdist but rather taking a GitHub tarball... That's fairly common for Linux distributions because for some odd reason they consider the sdist a binary and want to build directly from source, but without the SCM man_shrugging

Hi, so .. I just stumbled on this issue and I am wondering if the idea of what I did in [ansemjo/version.sh](https://github.com/ansemjo/version.sh) might be useful here? Note that I am not familiar with `setuptools-scm`, so I can't compare.

The gist is:
* you have a `$file` with a [`$Format:__$` string](https://git-scm.com/docs/gitattributes#_creating_an_archive)
* you add `$file export-subst` to `.gitattributes`
* on archive creation with `git archive` (i.e. also GitHub tarball downloads) the format strings get replaced and you can parse them for desired version information
* otherwise, if they were not replaced when you look at them, assume that you're working from a checked-out repository and can use `git`

In my example I use a `subprocess` call and the script itself obviously requires {`bash`,`dash`,`ksh`} – but the idea could probably be adapted to a pure Python implementation, too.

**Comment by FFY00** [comment]
Hi, the issue with that approach is populating the version in the build system as we don't use a `setup.py`, but instead a `setup.cfg`, which is a static configuration file and thus we can't run any code, as you have in your example (https://github.com/ansemjo/version.sh#python--setuptools).

See https://github.com/pypa/build/blob/master/setup.cfg

Thank you anyway :blush:

**Comment by layday** [comment]
> In my example I use a `subprocess` call and the script itself obviously requires {`bash`,`dash`,`ksh`} – but the idea could probably be adapted to a pure Python implementation, too.

There is a plug-in that does this for `setuptools-scm`; see https://pypi.org/project/setuptools-scm-git-archive/.

**Comment by ansemjo** [comment]
> There is a plug-in that does this for `setuptools-scm`; see https://pypi.org/project/setuptools-scm-git-archive/.

Oh wow, thanks!

> [...] instead a `setup.cfg`, which is a static configuration file and thus we can't run any code, as you have in your example.
> 
> Thank you anyway blush

Right, I understand. I saw `setup.py` getting mentioned, so I thought this could be in scope. :slightly_smiling_face:

**Comment by webknjaz** [comment]
> the issue with that approach is populating the version in the build system as we don't use a `setup.py`, but instead a `setup.cfg`, which is a static configuration file and thus we can't run any code

FTR this is not entirely accurate. Things like `setuptools-scm` can still get executed via setuptools' `entry_point`-based plugin discovery. It works just fine without `setup.py` at all but with `setup.cfg`, in this case, `setuptools-scm` also has its own separate configuration in `pyproject.toml` but that's another side of the story...

**Comment by FFY00** [comment]
Yes, what I meant is that we can't run code directly in `setup.cfg`. The build system, of course, may run external code, and it can opt to do so based on options we set in the configuration file.

**Comment by altendky** [comment]
It has its own problems but there is [Versioneer](https://pypi.org/project/versioneer/).  It addresses the tarball situation with a git export hook, fwiw.  I'm just surprised it didn't even get a mention in this long thread.  `:]`

**Comment by thomascobb** [comment]
> It has its own problems but there is [Versioneer](https://pypi.org/project/versioneer/)

Apologies if this is off topic, but a couple of years ago we found Versioneer too heavyweight for our liking, but liked the "put the git output parsing code in the repo instead of adding an extra dependency". We extracted the 100 lines we wanted and put it in a module [VersionGit](https://pypi.org/project/versiongit/) which supports version from git describe, git archive, sdist and wheel.

**Comment by RonnyPfannschmidt** [comment]
with git 2.32 archives get support for describe metadata it seems - https://github.com/pypa/setuptools_scm/issues/578
im going to take some time to make a release of setuptools_scm that supports those

**Comment by FFY00** [comment]
Can that setup be made to work with a fallback version when setuptools_scm is not installed? Essentially, I want to be able to build the project without setuptools_scm.

**Comment by webknjaz** [comment]
> Can that setup be made to work with a fallback version when setuptools_scm is not installed? Essentially, I want to be able to build the project without setuptools_scm.

Having `version = attr: some.callable` in `setup.cfg` should do that. Or just a hardcoded number. I think I saw somebody combining bumpversion with setuptools-scm like this.

**Comment by RonnyPfannschmidt** [comment]
> Can that setup be made to work with a fallback version when setuptools_scm is not installed? Essentially, I want to be able to build the project without setuptools_scm.

@FFY00 
Setuptools_scm can be a build requirement

**Comment by matthewfeickert** [comment]
> @matthewfeickert I think your project did that, right? Do you have any PR pointers?

We used to do this more, but @kratsg recently updated `pyhf` so that we use `setuptools_scm` for all version numbers and just use [`bump2version` for updating metadata in docs and config files](https://github.com/scikit-hep/pyhf/blob/e8a182d68fc268ab8b0f5a553317f6bf1c962047/.bumpversion.cfg)

- https://github.com/scikit-hep/pyhf/pull/1450
- https://github.com/scikit-hep/pyhf/pull/1480

but as Ronny mentioned

> Setuptools_scm can be a build requirement

we also have [`setuptools_scm[toml]>=3.4` as a build requirement](https://github.com/scikit-hep/pyhf/blob/e8a182d68fc268ab8b0f5a553317f6bf1c962047/pyproject.toml#L1-L3). We're happy to answer questions if people have any. :+1:

**Comment by henryiii** [comment]
You don't need `setuptools_scm` to build from SDist, as well - *just* when building from git.

**Comment by RonnyPfannschmidt** [comment]
@henryiii currently its always needed as its not modifying the sdist contents to not require its metadata

**Comment by benjimin** [comment]
+1 It would be a really great **default** if the build tool could manage the version string (using `git describe` where available, and potentially offering alternative methods or falling back to _warning or requiring user input_). So many projects vendor in `versioneer` just to avoid trying to manually maintain synchronisation between their version strings and VCS metadata, and that is always fragile (because it isn't how VCS is designed to be used, and a submodule can't control what tool/method is used to package it anyway).

**Comment by layday** [comment]
With the focus having shifted on making post-setuptools boostrapping easier, I don't think we'll be adopting setuptools-scm.
