### ISSUE TITLE
Build isolation by frontend

### ISSUE THREAD

**Issue by abitrolly** [pypa/build#208]
Just to throw in last commend to the locked https://github.com/pypa/build/issues/206#issuecomment-761008109 Don't feel like registering with https://discuss.python.org to continue the discussion. Maybe someone will just find it useful,

PEP 517 specifies that the role of frontend is to create an is `isolated environment for each build`. The discussion revealed that the spec didn't mean the build reproducibility, but merely the `virtualenv` to isolate packages that are used during the build from modifying user environment.

@pfmoore told that full `build isolation` was discussed somewhere with a decision that it is the role of the backend to care about it. No link was provided to check the claims and see if the specific mechanism for build isolation on frontend was discussed at all. Therefore I just record how I see it.

The universal approach that PEP 517 (and frontend) could do to provide complete build isolation, is to make the copy-on-write snapshot of the source tree. The more finegrained spec could try to define that source tree stays read only during build, or if that is deemed impractical, it could define writable locations for build artifacts, intermediate files useful for debug and caches. This will benefit CI systems, which could then plugin universal mechanism for discovery of built artifacts and caches for different backends.

**Comment by gaborbernat** [comment]
This discussion has little to do with this implementation of the spec (of which this tool is). It's the responsibility of the spec to pronounce on the topic. Posting here is like going to your local book club and shouting frustrated there about the state of law, rather than taking up the issue with your local representative who can actually help.

> @pfmoore told that full `build isolation` was discussed somewhere

It's probably somewhere on the packaging mailing list 5+ years ago. It's a public record you're free to investigate for it.

> The universal approach that PEP 517 (and frontend) could do to provide complete build isolation, is to make the copy-on-write snapshot of the source tree.

This proposal while might help with correctness is a very expensive operation. The copy might pull in a lot of files, making the build painfully slow to start. All because the backend has a bug of not being able to reset/maintain the state of its working directory.

> The more finegrained spec could try to define that source tree stays read only during build

This is technically unfeasible. There's no way for the frontend to make the source tree read-only in general and without causing unexpected side effects at the very least.

We get your proposals, but neither of those would be a step forward. I'm still of the opinion that it should be the responsibility of the backend, not the frontend. Mostly because the backend has the most and only accurate knowledge of what state it depends on. Here you pointed an example about the state of the source file tree, but they are many more global states that can make or break a build. What if the backend needs a given socket/pipe to work? Should the frontend manage that too? What about environment variables? What about system/user cache/application data paths? Should the frontend just make all that read-only? How would even the frontend know which of those the backend depends on? What about frontends that don't write content in the source tree? Should the frontend still bother with the expensive operation of copy/make it read-only?

**Comment by pfmoore** [comment]
> The copy might pull in a lot of files, making the build painfully slow to start. All because the backend has a bug of not being able to reset/maintain the state of its working directory.

Note that this is exactly what pip has done in the past. It's been an endless source of complaints from users where the result is, as @gaborbernat says, slow builds because of copying data that doesn't need to be copied for the build (the most obvious example is VCS history data, but large amounts of working data and virtual environments are also common.

Pip is switching to in-place builds precisely because the current behaviour has been unpopular with many of our users.

**Comment by FFY00** [comment]
I just want to point out again that the backend can do this if it needs to...

**Comment by abitrolly** [comment]
Changing the project desciption from `A simple, correct PEP517 package builder` to `Reference PEP517 package builder frontend` will clarify the scope of the project. I didn't really expect the builder to be a mere wrapper for other build tools.

**Comment by FFY00** [comment]
This is not the reference implementation, it is just a *simple* implementation. Its presence in the PyPA organization is simply because it is a useful packaging tool. If you want to write an alternative tool that does full isolation in order to achieve full reproducible builds without any external mechanism, you certainly can, you can even use the python module this package provides if you want. But that is not required by PEP 517, it'd be a project with a different scope.

**Comment by abitrolly** [comment]
I believe the common consensus from 20 years of lessons in financial industry is that writing spec without a reference implementation is a bad practice.

**Comment by gaborbernat** [comment]
I'll lock this as we're getting nowhere and as summed up before you're barking at the wrong tree 🌴.
