### ISSUE TITLE
[QUESTIONS] what does this log mean?

### ISSUE THREAD

**Issue by yamila-moreno** [pypa/build#265]
Hi! I'm testing with `build` and found an unexpected behaviour. Looking through the issues found some of them similar, but I didn't get to understand these logs.

I have a minimum project:
```python
# __init__.py
"""
test
"""
__version__ = "1.0.0"

def hi():
  print("hello, world"
```

and a `pyproject.toml` (generated with `flit`). When I run `python -m build` in the project, the log is as follow:

```sh
(.env) geliris :: ~/tmp/test » python -m build
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting flit_core<4,>=2
  Using cached flit_core-3.2.0-py3-none-any.whl (45 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: toml, flit-core
Successfully installed flit-core-3.2.0 toml-0.10.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/tmp/build-env-m6y7jfnb/bin/python -m pip install --upgrade pip' command.
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting flit_core<4,>=2
  Using cached flit_core-3.2.0-py3-none-any.whl (45 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: toml, flit-core
Successfully installed flit-core-3.2.0 toml-0.10.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/tmp/build-env-d9r2a1tg/bin/python -m pip install --upgrade pip' command.
```

I recognize two different virtualenvs like is the build done twice?
I assume these logs belong to the specific virtualenvs, can I suppress these logs?
Can I ensure the specific virtualenvs use the latest `pip`?

**Comment by FFY00** [comment]
The build is done twice, correct, but it's not the same build. Invoking build without passing either `--sdist`/`-s` or `--wheel`/`-w` will build both the sdist and wheel. So the backend will be invoked twice, once to build the sdist and once to build the wheel.
Because the builds may have different dependencies, they are built in different environments.

We will have better output handling in a future version, it will be hidden by default and only showed on fails.

You can't ensure the pip version in our isolated environment, if there is something wrong please report it.

**Comment by uranusjr** [comment]
It's probably a good idea to set `PIP_DISABLE_PIP_VERSION_CHECK=true` to avoid confusing the user.

**Comment by yamila-moreno** [comment]
ey @FFY00 thanks for the answer!!
