### ISSUE TITLE
Raw/Packager/No-network mode

### ISSUE THREAD

**Issue by flying-sheep** [pypa/build#293]
Hi, I’m currently on a mission to figure out a Linux/BSD distribution packager’s tookit of the future. I think this project and https://github.com/pradyunsg/installer/ make a good pair for standards-compliant building and installing of Python packages within a toolchain.

As Thomas said in https://github.com/pradyunsg/installer/issues/1#issuecomment-622970860, it’s not ideal for this use case to have a bunch of features that have to be turned off one by one to adapt building/installing to the requirements of a distribution packaging toolchain.

I think so far to get the desired behavior, one can use

```py
python -m build --skip-dependencies --no-isolation -o "$destdir" "$srcdir"
```

But I fear this might grow and older builds might break (see e.g.  #145). Is it possible to either

1. guarantee that this commandline will always result in the intended behavior, or
2. add a flag that says “I want to build only with what’s currently installed and available, and e.g. make no attempts to resolve dependencies or download anything”.

   I.e. a flag that which combines the above flags and all possible future flags influencing this use case.

**Comment by layday** [comment]
Why do you want to skip the dependency check?  This does not install dependencies; it only checks that they are satisfied and errors out if they aren't.

**Comment by FFY00** [comment]
This is what the `--no-isolation` flag does, it will simply invoke the backend. I would recommend you to not pass `--skip-dependencies`, as it will error out if some dependency is missing, possibly preventing obscure issues where the backend might not actually fail. The use-case for that flag is mostly when bootstraping the project itself, as it drops the `packaging` dependency.
The reason I wrote this tool in the first place was for *distro packaging*, it then grew a bit, and we switched the default behavior to provision a virtaul environment and build the package there, as that's best for normal users.
`--no-isolation`/`-n` will stay this way, almost certainly for the entire lifetime of this project, so that is something you can rely on.

What you probably want to do is
```
python -m build -nw
python -m installer ...
```

**Comment by flying-sheep** [comment]
> It might be an idea to rename this to `--skip-dependency-check`

ah yes, it not being named that and me not reading properly led to the misunderstanding. Thank you for the clarification!
