### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by FFY00** [pypa/build#305]
Python 3.5 is EOL, should we drop support for it now?

cc @pypa/build-team

**Comment by henryiii** [comment]
But keep support for Python 2.7? You gain almost nothing I expect dropping 3.5 but keeping 2.7 - the real gains come from being able to write 3.6+ code, which we can't now due to 2.7.

Of course, exactly the same argument can be applied to 3.4 and even 3.3.

In the PyPA, Setuptools, setuptools_scm, pip, packaging, manylinux, cibuildwheel, pipx, and twine are 3.6+; pipenv and virtualenv are 2.7/3.5+. Fine by me either way, just thought I'd address the :Lee

**Comment by gaborbernat** [comment]
I'm happy to drop support for 3.5. And also 2.7. I'm ok to separate those two.

**Comment by layday** [comment]
Not much point from a maintenance perspective like @henryiii said if 2.7 remains, but at least our CI's gonna run in a bit less time :)

**Comment by layday** [comment]
@FFY00, do you have some idea for when you'd like to drop support for 2.7?

**Comment by gaborbernat** [comment]
IMHO let's drop both today.

**Comment by FFY00** [comment]
I'd like to get #142 in Python 2, but that is something I can backport afterwards. If there are any big issues, we should also backport fixes to the last version to support Python 2. I'll defer to you (the other maintainers) to make the decision.

**Comment by henryiii** [comment]
Personally, I found backporting to an LTS Python 2 branch to be effective in several projects (cibuildwheel & boost-histogram). It's pretty easy (just always immediately backport CI fixes!), and it frees up the main development branch, making it easier to work with static types, add features, unpin stuck dependencies, etc.

I'd recommend using pyupgrade in pre-commit to help with the drop if you aren't already, @layday.

**Comment by henryiii** [comment]
Also, since build is a *build* tool, you can build universal packages from Python 3. So you really are only stuck with the older LTS build if you are building a Python 2 only package (rare) or a binary Python 2 package (FYI the LTS cibuildwheel doesn't support build, it was added in 2.0.0a4).
