### ISSUE TITLE
py.typed file missing from package

### ISSUE THREAD

**Issue by srittau** [pypa/build#319]
Please consider the following (shortened) `setup.cfg` file:

```
[metadata]
# ...

[options]
packages = sqla_utils
include_package_data = True
# ...

[options.extras_require]
# ...

[options.package_data]
* = py.typed
```

When building the package with build 0.4.0, the wheel package will contain the `py.typed` file, while the source package won't. After upgrading to 0.5.0, neither package will contain it (likely because the wheel is now built via the source package.)

**Comment by gaborbernat** [comment]
This is by design. These types of bugs are exactly the kind we want to catch by building for source. You should ensure your sdist contains the `py.typed` file and that way your wheel will also.

**Comment by FFY00** [comment]
> the wheel package will contain the `py.typed` file, while the source package won't.

That is an issue! Because if I download your sdist and try to build a wheel from it, which is the whole point of sdists!, now we have a different, broken, wheel :sweat_smile:

The new default behavior in 0.5.0 is meant to catch these issues.

**Comment by layday** [comment]
The issue is that `include_package_data` conflicts with `options.package_data`.  The former takes precedence and instructs setuptools to read the package data from `MANIFEST.in` and ignore `options.package_data` - if you remove it `include_package_data`, it'll work.  My personal advice is, if you can help it, just don't use setuptools.

**Comment by srittau** [comment]
Thank you for pointing out the correct way to fix this.
