### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by sometato** [pypa/build#385]
Does build have any kind of support for reproducible builds? I did two builds, back to back, and the checksums were different.

flit seems to have this with its `SOURCE_DATE_EPOCH` environment variable: https://flit.readthedocs.io/en/latest/reproducible.html

**Comment by FFY00** [comment]
We just prepare the environment and invoke the backend, so the only bit where we could be unreproducible is in the environment -- the versions picked happen to be different, though I only think this will happen if some of the dependencies get new releases after the 1st build.

I'd say your issue here should be your backend, not us.
