### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [pypa/build#468]
Could you please make a new release (with py3.11 fixes)?

**Comment by henryiii** [comment]
I'd like to soon - I really want to get the error message improvements out soon too. I've got a little bit of simple polish I want do apply after #460 (waiting on that due to the tests currently blocking any other development on pypa when they run). @FFY00 I don't have maintainer rights on PyPI (I'm `henryiii` there) or while we are at it, readthedocs (also `henryiii` there). @layday and @gaborbernat, anything else you'd like in a 0.8 release?

**Comment by gaborbernat** [comment]
I'm happy to release current main 👌 as is.

**Comment by FFY00** [comment]
I can do a release later today. I still haven't automated the release process because it involves more than just uploading to PyPI.

**Comment by henryiii** [comment]
@FFY00 when you release, could you jot down the steps? That would be helpful, I think. Something like https://github.com/pybind/pybind11/blob/master/docs/release.rst or https://github.com/scikit-hep/boost-histogram/blob/develop/.github/CONTRIBUTING.md#common-tasks.

**Comment by FFY00** [comment]
Sorry for the delay. 0.8.0 should be out now. I will make a PR documenting the release process.
