### ISSUE TITLE
Support `build_editable`

### ISSUE THREAD

**Issue by samuelcolvin** [pypa/build#500]
when trying to install with `pip install -e .` I'm getting

```
ERROR: Project file:///home/samuel/code/python-devtools has a 'pyproject.toml' and its build 
backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', 
it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

Until this, `build` seemed great, but editable builds are core part of my development workflow, how hard would it be to support them?

**Comment by layday** [comment]
Hooks are implemented by backends, such as setuptools or Poetry. build is a build frontend. `pip install -e .` doesn't interact with build at all - it interfaces directly with pep517, a lower-level frontend.  The error you are getting is not from lack of support for `build_editable` in pip (or its dependencies) - it's because you don't appear to be using setuptools and have not declared an alternative backend, such as Poetry.

**Comment by layday** [comment]
Okay, I see that you are using setuptools with `pyproject.toml` configuration. Editable support without `setup.py/cfg` hasn't landed in setuptools, see https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904.

**Comment by samuelcolvin** [comment]
thanks sorry for the noise, wrong place.

**Comment by layday** [comment]
No worries.
