### ISSUE TITLE
`error: Multiple top-level packages discovered in a flat-layout`

### ISSUE THREAD

**Issue by patrick-kidger** [pypa/build#611]
So I understand that `setuptools` and `python setup.py sdist bdist_wheel` are being deprecated in favour of `pyproject.toml` and using `python -m build`. In my project I've deleted `setup.py` and transitioned everything into `pyproject.toml`.

Now I have a few other top-level folders, so I get the titled error message when running `python -m build`. The guidance I find online suggests resolving this by adding a `tools.setuptools.packages` entry to my `pyproject.toml`, and indeed this works.

But, of course, I'm making this transition precisely to avoid using setuptools in the first place! I assume that adding a `setuptools` entry is probably not going to be compatible for very much longer.

What is the appropriate way to work around this that depends only on `build`, and not on `setuptools`?

**Comment by henryiii** [comment]
`setuptools` is not deprecated at all. Calling `python setup.py <stuff>` is, but not setuptools itself.

To build a package you need a backend and a frontend. A backend is responsible for creating SDists and wheels. Setuptools is a backend, as is hatchling, flit-core, pdm-backend, and others. You pick one of those. My favorite is hatchling, as it's simple, has good defaults, and is extensible. Setuptools has 40K+ lines of code, a lot of legacy issues, a dependence on distutils via inheritance, and has a tendency to be pinned or restricted in some environments (NumPy publicly recommends capping to <60, for example, because they don't want to continue to support it!). But it's still a fine choice.

The frontend is the "new" thing, and replaces `python setup.py` commands. To build an SDist you can use `build`, and to build a wheel you can use `build` or `pip wheel`. `pip install` is also a frontend. PDM is also a front-end as long as your backend uses PEP 621 (everything expect Poetry and setuptools < 62 supports it now). I think Hatch will also get this general support soon. Etc.

The front end knows nothing of packages, etc. That's all handled by the backend. The front end handles setting up the isolated build environment and passing in `config-settings`.

Anyway, in your case, pretty much all backends will need some guidance if you have multiple top level **packages**. (If it's only folders, and you have one package, try placing it in `src/<package_name>`, that's also [better anyway](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/#:~:text=The%20src%20layout%20helps%20prevent,item%20on%20the%20import%20path.)). You'll sometimes have a little backend-specific configuration in pyproject.toml, and that's fine. It just makes switching backends a little harder, but that's not something you do very often, and it's way easier than if we didn't have `[project]`.

**Comment by patrick-kidger** [comment]
Ah, the deprecation of `setup.py` but not `setuptools` was a subtlety I wasn't aware about, thank you.

I've just taken a look at the docs for hatch/hatchling, but I didn't see anything really explaining what its scope is / how it compares to existing tools. As best I can determine its meant to be an all-in-one replacement for setuptools (build system) + twine (publishing) + conda/venv/rye/etc. (environments)?

I don't really have strong feelings about the choice of build system; anything that packages up code ready for `twine` is good enough for me. I'll stick to setuptools (and use the `tools.setuptools.packages` flag) for now, and wait to see how this all shakes out in the long run. [(C.f. also this discussion thread on rye.)](https://github.com/mitsuhiko/rye/discussions/6)

Thanks again for your help!

**Comment by henryiii** [comment]
Those are two things: hatchling is a simple, extendable build backend. I'm quite fond of it and it's the first choices at https://scikit-hep.org/developer/pep621 and https://packaging.python.org/en/latest/tutorials/packaging-projects/.

Hatch, on the other hand, like Poetry and PDM, is all-in-one tool for developing Python packages. The feature it has that the other two doesn't is multiple environments, making it a replacement for tox/nox. But it doesn't (currently) have environment locking, so it's a tradeoff. You don't need to use Hatch to use hatchling - the only reason I reach for a tool like that is for the lock files, so I use PDM + Hatching if I use one of them at all (usually only for "applications" like websites).

**Comment by abravalheri** [comment]
Hi @patrick-kidger, I just wanted to clarify this:

> Ah, the deprecation of setup.py but not setuptools was a subtlety I wasn't aware about, thank you.

Please note that `setup.py` is a perfectly valid, not deprecated, configuration file. What is deprecated is using it as a CLI tool. [TL;DR](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) please use `python -m build` instead of `python setup.py sdist bdist_wheel`.

**Comment by patrick-kidger** [comment]
Thanks for the clarifications! It looks like Python packaging continues to have its usual collection of subtleties and footguns :D

FWIW I actually couldn't figure out the correct setuptools incantations, so I took @henryiii's suggestion and switched to hatchling; this just meant adding
```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["my_package_name/*"]
```
to my `pyproject.toml`.

Anyway, this may not be a problem for very much longer. rye seems to have gotten a lot of recent traction, so I'm looking forward to seeing where that goes.

**Comment by henryiii** [comment]
Rye is a frontend, not a backend. So it replaces PDM and things like that. I believe you still pick a backend. It might default to Maturin.

**Comment by henryiii** [comment]
I might have mentioned it somewhere, but `check-sdist` is useful for checking to see if the SDist contains what you think it should.
